[package]
name = "l1-1"
version = "0.1.0"
edition = "2021"
authors = ["Denis Zakharov"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gag = "1.0.0"